[package]
name = "kudu"
version = "0.2.1"
edition = "2024"
license = "GPL-3.0-or-later"
description = "Easily manage VMs on Linux"
readme = "README.md"
homepage = "https://github.com/pythops/kudu"
repository = "https://github.com/pythops/kudu"

[dependencies]
lazy_static = "1.5.0"
crossterm = { version = "0.29", default-features = false, features = [
    "events",
] }
ratatui = "0.30"
tui-input = { version = "0.15", features = [
    "crossterm",
], default-features = false }
dirs = "6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive", "cargo"] }
anyhow = "1"
chrono = "0.4"
strum = { version = "0.28", features = ["derive"] }
uuid = { version = "1", features = ["v4", "serde"] }
libc = "0.2"
reqwest = { version = "0.13.4", features = ["blocking", "stream"] }
qapi = { version = "0.15", features = ["qmp"] }
which = "8"
kvm-ioctls = "0.25.0"
rustix = { version = "1", features = ["fs"] }
rand = "0.10"

[profile.release]
lto = "fat"
strip = true
codegen-units = 1
